title: David Basoco
email: basoko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  David Basoco personal site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://basoko.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: davidbasoko
github_username:  basoko
assets_path: /assets
# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
